site_name: FAIRmat Tutorial 16
site_description: |
  Tutorial 16  materials
site_author: FAIRmat Area F
repo_url: https://github.com/siamakn/temp_tutorial_16
edit_uri: ""

nav:
  - Home: index.md
  - Tutorial 16:
    - Document Your Research: T16_X/T16_X_document_your_research.md

plugins:
 - search
theme:
  name: material
  palette:
    primary: '#2A4CDF'
    accent: '#008A67'
  font:
    text: 'Titillium Web'
  logo: assets/fairmat-logo.png
  favicon: assets/favicon.png
  features:
    - navigation.instant
    - navigation.footer
    - content.code.copy
  custom_dir: docs/theme
markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - toc:
      permalink: True
  - pymdownx.arithmatex:
      generic: true
  - attr_list
  - mkdocs-click
  - pymdownx.extra
extra:
  generator: false
  homepage: https://www.fairmat-nfdi.eu/fairmat/
use_directory_urls: false
extra_css:
  - stylesheets/extra.css
extra_javascript:
#  - javascript.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
